name: XO Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *' # يعمل كل 4 ساعات
  workflow_dispatch: # يتيح لك تشغيله يدوياً من زر Actions

concurrency:
  group: xobot-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # هذه الحزم ضرورية لعمل مكتبات معالجة الصور sharp و tesseract
          # وضفنا ffmpeg هنا عشان الصعود على الاستيج
          sudo apt-get install -y tesseract-ocr libtesseract-dev libvips-dev ffmpeg

      - name: Install dependencies
        run: |
          # نستخدم npm install لأنه لا يشترط وجود ملف package-lock.json
          npm install

      - name: Run Bot
        env:
          U_MAIL: ${{ secrets.U_MAIL }}
          U_PASS: ${{ secrets.U_PASS }}
        # يقوم هذا الأمر بتنفيذ ما هو موجود في "scripts": { "start": ... } داخل ملف package.json
        run: npm start
